### PR TITLE
Make sure `tableViewHeight` isn't less then 0.0 to prevent crash

### LINKED ISSUE #51: Crashing on changing orientation while UISearchController is active
Hi, 
I tried using your library, it's looking very nice, but has a little problem when changing the device orientation while the `navigationItem.searchController.isActive = true`.
This is the error I'm getting in the console:
```
*** Assertion failure in -[HGPlaceholders.TableView _classicHeightForRowAtIndexPath:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3698.84.16/UITableView.m:15329
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid row height provided by table delegate. Value must be at least 0.0, or UITableViewAutomaticDimension.'
```
After some debugging I'v noticed that the hight from the delegate is `-119`:
image
So I tried the most obvious thing, I'v added `tableViewHeight = tableViewHeight >= 0.0 ? tableViewHeight : UITableView.automaticDimension` before the method return (line 154), but guess what?
**Somehow the value is still `-119`** 😓
So I thought maybe the `UITableView.automaticDimension` is also returning `-119`? so let's try just `tableViewHeight = 0`.
No, it didn't worked, `tableViewHeight` was still `-119`. 😧

Hope you'll be able to reproduce and detect how to solve this problem.
I didn't understand yet how is that possible to change the value by this way (`tableViewHeight = 0`) and it won't change, like this line doesn't exists. 😨

Thanks,
Ido.

### PR DESCRIPTION
**Pull request by Idomo**
Fix #51 
From some reason, the fix I've tried a long time ago with iOS 13 and didn't work, now working with iOS 15.

### CODE REVIEW

File: HGPlaceholders/Classes/Protocols/NibLoadable.swift [hunk 1]
```diff
@@ -16,7 +16,7 @@ import UIKit
  *
  * to be able to instantiate them from the NIB in a type-safe manner
  */
-protocol NibLoadable: class {
+protocol NibLoadable: AnyObject {
```
Comment (HamzaGhazouani) [inline HGPlaceholders/Classes/Protocols/NibLoadable.swift:19]: @Idomo  Any reason to use `AnyObject` instead of `class`?

**Comment by HamzaGhazouani** [comment]
Thanks @Idomo  for fixing that :)

File: HGPlaceholders/Classes/Protocols/NibLoadable.swift (hunk 1 above)
Comment (Idomo) [reply HGPlaceholders/Classes/Protocols/NibLoadable.swift:19]: As of xCode 13 there is a deprecation warning: `Using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead`

**Review by HamzaGhazouani — APPROVED** [review]
